### ISSUE TITLE
bootstrap 4

### ISSUE THREAD

**Issue by nicolain06** [Kademi/keditor#106]
Hello, is there any update to work with boostrap 4 instead of boostrap 3?

Otherwise, is there any way to load JS using the iframe mode (exactly as with the contentStyles method for CSS)?

**Comment by ducdhm** [comment]
@nicolain06 
About Bootstrap 4, we dont have any plan yet but acctually, you still can use bootstrap 4 as content snippets

For your second question, we have a callback named `onInitFrame`. You can use this callback for your stuff.

```
    ...
    // Callback will be called after iframe and content areas wrapper inside it are created. Arguments: frame, frameHead, frameBody
    onInitFrame: function (frame, frameHead, frameBody) {
    },
    ...
```

**Comment by ducdhm** [comment]
@nicolain06 Let me explain about the iframe first. There are 2 types of iframe:
 * External iframe with `src` attribute: with this kind of iframe, all you need is specifying src (external URL) for it. And you *CAN NOT* do anything with it because of security issue.
 * Internal iframe: with this kind of iframe, you can 100% control it by yourself. And KEditor uses this kind of iframe to handle `iframeMode`.

Let's talk more details about `internal iframe`. As I mentioned above, you can do anything with it via JavaScript like adding content for it, add inline, internal or external css for it too. *BUT* you can't add `<script></script>` for it. But you can use loaded `script` in parent window.

Example: You want to do something with bootstrap tabs in iframe (consider you already included js stuff for bootstrap tab). 

```
    // In onInitFrame callback, you will init tab
    onInitFrame: function (frame, frameHead, frameBody) {
        frameBody.find('bootstrap.tab').tab();
    }
```

That's it. So simple, isnt it?
