### ISSUE TITLE
Gen 2 of KEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#109]
Changes:
 * `Add button` at bottom of `container` or `content area` to allow user to add container or component
 * When click `Add button`, a modal will be showed. The snippet will be depends on which `Add button`. Can be `container`, `sub container` or `component`.
 * Remove snippets list in sidebar
 * When click on setting icon, will show sidebar with setting forms

Related to https://github.com/Kademi/kademi-dev/issues/2922

**Comment by bradmac** [comment]
Great stuff! The main thing is to not use drag and drop for adding components, because its really hard to get them in the right positions, especially now we have nested containers.

Instead we want partially transparent buttons at the end of each container the user can click or tap to insert, which displays a full screen modal of containers and components. The user taps a container or component and its instantly added to the location of the Add button they clicked. So no dragging or dropping for insertion.

I think the list of containers and components should be a single list, rather then using 2 tabs. User's dont really understand the difference so its easiest to just let them see and choose whatever they want from one list.

However, users should still be able to move with drag/drop as they've always done.

The sidebar should be initially hidden, but displayed for editing properties.

Also, i would like to enable editing of pages in-place. Eg if I'm viewing a page i can click an edit button, and the editable section of the current page is made editable in keditor. Page elements outside the editable area should be unchanged.

**Comment by anhnt** [comment]
Yup we got issue with inline editor https://github.com/Kademi/kademi-dev/issues/5392

**Comment by bradmac** [comment]
> What do you think about editing text of text component in setting instead of editing inline

That would make our users very sad. It would be a big step backwards, and would make keditor inferior to editors in other platforms.

CK editor fully supports inline editing so i dont think there's any reason to stop doing this:
https://ckeditor.com/ckeditor-4/#inline

**Comment by bradmac** [comment]
Problem is that sits over the edited area. 

We would need to limit the content area to be beside and not under the sidebar. This is ok for mailchimp because it only does emails which is always narrow content. But we're supporting web pages which need the full width to be available.

But also and more importantly this would dis-associate the editor toolbar from the content being edited so would be inferior UX. This is exactly why ckeditor supports inline editing, to give users a good UX where the toolbar is right above and attached to the thing it applies to.

**Comment by ducdhm** [comment]
@bradmac I think we should hide some plugins from CKEditor like Video, Audio, Image and Youtube. We already have them as components. It'll make CKEditor toolbar more elegant.

**Comment by bradmac** [comment]
We definitely need the image toolbar to still be there, thats often used in ckeditor content in ways that components cant replicate, eg when flowing text around an image.

In theory video and audio could be the same, but in reality these are very rarely used like that, so i think we can remove them.

But thats just a default, users of keditor can choose which plugins to enabled with ckeditor right?

**Comment by ducdhm** [comment]
Mockup for Gen 2:
1. Button add `container`, `subcontainer`, and `component`
![content_editor_page](https://user-images.githubusercontent.com/1289631/39566872-3d097830-4ee7-11e8-9690-39396af20647.png)

2. Modal for snippets
![show_modal](https://user-images.githubusercontent.com/1289631/39567014-c2a6d97e-4ee7-11e8-8161-78b9060d459f.png)

3. Settings sidebar
![show_setting](https://user-images.githubusercontent.com/1289631/39567026-c9fa9c24-4ee7-11e8-9dba-c53b10b30367.png)

**Comment by ducdhm** [comment]
@anhnt @bradmac @paddyow v.2.0.0-alpha is READY TO TEST. Let's check it out https://rawgit.com/Kademi/keditor/gen-2/examples/index.html

**Comment by bradmac** [comment]
Just seeing this error in FF, but not in Chrome. Error occurs on clicking the Add button
![image](https://user-images.githubusercontent.com/826458/40641484-f0a66836-636d-11e8-9ce1-800a71ea7a98.png)

On this demo - https://rawgit.com/Kademi/keditor/gen-2/examples/basic_with_blank_content.html

**Comment by bradmac** [comment]
Also, see this previous comment. I think this is important, I'm seeing this confirmed with all users.

> I think the list of containers and components should be a single list, rather then using 2 tabs. User's dont really understand the difference so its easiest to just let them see and choose whatever they want from one list.

Can we merge containers and components to a single list?

**Comment by bradmac** [comment]
And i think its important to make the add buttons partially transparent, so they dont distract from the content

> Instead we want partially transparent buttons at the end of each container the user can click or tap to insert,

**Comment by ducdhm** [comment]
@bradmac 
> Can we merge containers and components to a single list?

I think it can make user confused. Because:
 * If they choose components and there is no container, what will happens?
 * If they choose containers, they only see new section with cols and other add buttons. It's OK?

**Comment by ducdhm** [comment]
- Add opacity for add button ✔️ 
 - Fix issue when adding container in Firefox ✔️

**Comment by bradmac** [comment]
> If they choose components and there is no container, what will happens

I think we can either:
- filter the list to only show containers when adding outside a container
- OR, allow adding components in any position, if being added at top level wrap it in a single col container

I think the second option would be most intuitive for users, they often dont understand containers initially

**Comment by remcovog** [comment]
Gen2 looks a bit like sirtrevor JS approuch. When you populate the layout with column blocks, it gets a bit messy / confusing with all the + buttons on the screen, and becomes less wygiwys...  Personally I loved the simple style with the right toolbar, always everything on screen, no popups blocking the page etc.

Small suggestion for improvement. When a component has configurabele options, load this button onhover in the center of the component, instead between the other options
Quick screenshot of what i mean:

![afbeelding](https://user-images.githubusercontent.com/12196581/40644487-b242b850-6323-11e8-982d-a2f355b9844b.png)

**Comment by bradmac** [comment]
> Small suggestion for improvement. When a component has configurabele options, load this button onhover in the center of the component, instead between the other options

:+1: 

Regarding the add button approach vs drag/drop from right panel, our feedback from users has been unequivocal, that placing items with drag and drop is a massive pain, especially since keditor got sub-containers. Also the right panel layout is fine for a small number of components, but when there are many (eg 50 or more) users need screen real estate to find them.

The new layout looks very messy because
- no opacity on the buttons
- having seperate buttons for components and containers is too busy

But @ducdhm has actioned the first and i think is doing the second

We could also have styling which makes the add buttons only visible on hover. I'm generally opposed to this because we want first class support for touch devices which cant rely on hover, but it could be conditional and only use hover display on non-touch devices .. ?

**Comment by remcovog** [comment]
Toggle the visiblity of the buttons enabled by touch-device or not, sounds like a good solution, creating the best workflow for both worlds. If the button onhover will be showed, you must prevent the jumping effect of the page when hovering over multiple components/layouts. But this might be a great approuch adding the functionality, and keep the workspace clean.

**Comment by ducdhm** [comment]
@bradmac we have 2 cases for add button
 * In content area and container, we can add container/sub-container and component
 * In sub-container, we can add only component

If we unify just a button for adding, when click add button in sub-container, users can see only component snippets, but they can see both component and container snippets when click add button in content area and container. It's good UX?

**Comment by bradmac** [comment]
> If we unify just a button for adding, when click add button in sub-container, users can see only component snippets, but they can see both component and container snippets when click add button in content area and container. It's good UX?

Good UX is that the user can see what they're able to do. In whatever context they click the Add button they should see a single list containing all the things they can add.

**Comment by ducdhm** [comment]
@bradmac I researched and analyst a lot of other content builder or web builder, so I can recommend other idea for keditor.
 * For each content area, I'll put a button at bottom with icon and text "Add container" (layout or section or ....)
 * In side container, just a button at bottom, click on this button, we can add either sub-container or component. Containers are showed above and component are below.

It's good idea, isnt it?

**Comment by bradmac** [comment]
I actually had a new user tell me today they were using the EDM editor (original keditor) and couldnt figure out why they couldnt add a component to the screen. I explained they needed to add a container first.

That was a developer, so this really confirms to me that users initially dont understand the difference between containers and components. So just an add button which shows a filtered list of what they can add is really important.

So I think the best option is:
- have a single button at each point where something can be inserted. This should just be a simple plus icon.
- when thats clicked display a full screen modal with all of the things that can be inserted at that location. 

Additionally, i think it would be nice  to allow components to be added at a top level, and just wrap them in a col-12 container. Its a very common use case, especially for edms.

**Comment by ducdhm** [comment]
@bradmac Everything is done! You can check latest code in action at [here](https://rawgit.com/Kademi/keditor/gen-2/examples/)

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
@bradmac Do you need me to integrate new version to Kademi?

**Comment by lstandish** [comment]
Great project!
I like "explicit snippets" best.  I think it makes the page building process clearer even to complete novices. "Implicit snippets" shows both containers and components together and, I think, encourages confusion in the mind of the novice.  That is, it hides the nature of containers and components and delays understanding..

**Comment by EadHassan** [comment]
Hello,
Where I can download [this version](https://rawgit.com/Kademi/keditor/gen-2/examples/)

**Comment by ducdhm** [comment]
Done!

**Comment by kprasadbabu7** [comment]
![image](https://user-images.githubusercontent.com/44153959/77731929-e23f7100-7029-11ea-87fc-2154686584ce.png)


Page not found  please check this

**Comment by PrasadCertprime** [comment]
how to add a background image
