### ISSUE TITLE
Device width selection

### ISSUE THREAD

**Issue by bradmac** [Kademi/keditor#112]
It would be awesome if we could add device width selection to the editor, so we can see how the content will look on different devices while in the editor

I think this would be 3 buttons - smartphone, tablet, desktop

Probably along the top of the editor

Thoughts?

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/39903173-f53cbbbc-5525-11e8-963a-210533fdec83.png)

**Comment by ducdhm** [comment]
Or maybe let me do a little example in keditor for this feature. It'll be cool if people knows that we also have preview feature 😃

**Comment by bradmac** [comment]
What i'm thinking is that this will still be part of the editor, ie the editor canvas displaying the content would be narrowed, but the edit features will still be active.

I think that would be a powerful feature to assist with editing

**Comment by Williammonte7** [comment]
Good afternoon friend bradmac,  saw your print and noticed that its Kademi/keditor has amazing features such as Save, Edit and select Page. I imagine that must have given work to reach this level. I would like to know if you have how to share i'm starting now and these improvements made by you would help me a lot.

**Comment by bradmac** [comment]
Hi @Williammonte7 great to hear you like it! there's some getting started docs here - https://github.com/Kademi/keditor

**Comment by ducdhm** [comment]
New UI:
![Clipboard - June 12, 2019 5_02 PM](https://user-images.githubusercontent.com/1289631/59344354-1f0ad780-8d38-11e9-9f6c-45e8cd44561c.png)

New options:
![Clipboard - June 12, 2019 5_04 PM](https://user-images.githubusercontent.com/1289631/59344358-2336f500-8d38-11e9-92c4-5a8fa4273d00.png)

**Note**: `iframeMode` is removed because we need iframe to change device width.
