### ISSUE TITLE
Gen 2: Make add button visible when hovering via container or component

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#155]

**Comment by bradmac** [comment]
hey @ducdhm something which might be worth considering, is that currently the add buttons only allow adding at the end of each container. If i want to add a component to the middle of several components i need to add it to the end and then move it.

This is necessary in the current UI because otherwise the page would be too messy

But if we show add buttons on hover, then it might be reasonable to show add buttons at every point where a component can be added, so at the top and bottom of a container, and between each component.

What do you think?

**Comment by ducdhm** [comment]
New UI:
![image](https://user-images.githubusercontent.com/1289631/60197514-b9efcf80-9869-11e9-9734-76807aae2e48.png)

Rules:
1. Add button for content-area is always visible
2. Add button for container-content is visible when container-content is empty
3. Add button after component or sub-container is visible when hovering
