### ISSUE TITLE
Split Containers and handle like Components [Feature request]

### ISSUE THREAD

**Issue by Filipetb** [Kademi/keditor#230]
Hi guys,

Why not handle containers like components?

I mean, isn't better to handle inside the source code instead of in Keditor initialization overwriting the defaults options? What you guys think about?

Also, why not have snippet for Sections/Containers, Rows and Columns separated?

I am trying create a SettingForm for section/container, rows and column changes, but are all together inside a container. It's difficult to create a nice UX/UI that way because is too much things together to edit. What you guys think about?

Just trying to come with some questions to think some ways to improve the software =)

**Comment by ducdhm** [comment]
@Filipetb 

> Why not handle containers like components?
KEditor wants to separate 2 concepts, container as layout and component as UI. Just simple for end-user.

> Also, why not have snippet for Sections/Containers, Rows and Columns separated?
Sometimes, users do not know that they need to add Sections/Containers first and then Rows and Columns and then other component like photo, text, etc... It's so complicated for them. That's why we just provide a lot of container snippets such as col-5 + col-7, col-3 + col-3 + col-3 + col-3,etc... And KEditor also allow users to drag n drop to resize the column. So... it's UI/UX view points of KEditor team, so if you dont agree with us, so... KEditor is open-source and you can create your own component like Section, Container, Row or Column component. Guideline for create your own component and container as following links:
 * https://github.com/Kademi/keditor/blob/master/docs/custom_container.md
 * https://github.com/Kademi/keditor/blob/master/docs/custom_component.md

> I am trying create a SettingForm for section/container, rows and column changes, but are all together inside a container. It's difficult to create a nice UX/UI that way because is too much things together to edit. What you guys think about?
Can provide me your list of setting? In Kademi, we have a lot of settings for container like  background color, background image, background-size, background-repeat, padding, margin, parallax scroll, class, inverse color, height, etc... But they're well-organized (with collapse too), users are still happy with it so I think there are no big deal when you have a lot of settings. Except you make your setting forms so badly and hardly to use ;)
