### ISSUE TITLE
how to set content dynamically....

### ISSUE THREAD

**Issue by ccwalkerjm** [Kademi/keditor#63]
Very nice project....I have an issue.
How do you set the content that you previously saved?    

Essentially you initially saved the content and then you want to resume editing, how do you set the content dynamically with the saved content?

**Comment by bradmac** [comment]
You should save your content with some ajax service provided by your server, and then reload it either by ajax or by generating the content into your page with server side templating.

**Comment by ccwalkerjm** [comment]
Thanks Brad for the feedback.  I understand how to save the content....The issue is how to re-append the content so that I can continue editing......The scenario is this;;;;;started to build a site....then save the content....close builder ....restart builder......append save content...continue to build etc......

**Comment by ccwalkerjm** [comment]
I guess the question is "How do I reload content"  dynamically using jquery?  Could you give me an example?..

**Comment by ccwalkerjm** [comment]
After much hacking I was able to resolve the problem by writing a method in keditor.js.    

reset: function(options) {
      return $(this).each(function() {
        var target = $(this);
        flog('Initialze KEditor', target, options);
        var keditor = new KEditor(target, options);
        target.data('keditor', keditor);
      });
    },

Essentially this reset the content.  I can now dynamically set the content.   

This is essentially the same as the __init function.

**Comment by ducdhm** [comment]
@ccwalkerjm I'll add method to setContent for keditor

**Comment by ccwalkerjm** [comment]
Much appreciated....whats the timeframe...

**Comment by robw-ddsn** [comment]
Hey there... Just adding my support and thanks in advance for this issue. setContent will be perfect.

Meanwhile we had to take a slightly different approach because of the way we load content (from a parent document containing an iframe with keditor in it). We thought of setting the content of the content area and re-initialising the editor, but this produced strange results because keditor obviously sets up stuff in the DOM on initialization that didn't like us doing that. We found we had to completely destroy the content area, re-create it and re-initialize keditor.

ccwalkerjm's approach looks better, but maybe our approach will help someone meanwhile.

Please pardon the mix of jQuery and classic JS. It's where I came from... ;)

<div id="ContentAreaContainer">
    <div id="ContentArea"></div>
</div>

// KEditor doesn't have a way to re-populate content or destroy itself, so we need to manually destroy the content area and re-initialise it every time it's updated from outside
$('#ContentArea').remove();

var strLoadContent = ''; // Set the initial content here
var oContentArea = document.createElement('div');
oContentArea.id = 'ContentArea';
oContentArea.innerHTML = strLoadContent;
document.getElementById('ContentAreaContainer').appendChild(oContentArea);

$('#ContentArea').keditor({
    // options
});

**Comment by rihanrahul** [comment]
@ccwalkerjm If you want to edit the content later, I think you dont need to add any other methods. Just load previously saved data before initilializing the builder. Thats it!

**Comment by Padawan2200** [comment]
I encountered the same problem, i need to set content to the editor after it was already initialized.
The solution is to set the content with jQuery html and create the keditor component.
The only thing you must take into account in order to be able to drag and drop snippets is to update the containers for drag&drop.
Something like this:

$('#ContentArea').html(newContent);

$('#ContentArea').keditor({
    onReady: function() {
        var snippetsList = $('#' + this.options.snippetsListId);
        if (snippetsList.length>0) {
            snippetsList.find('.keditor-snippet[data-type^=component]').draggable('option', 'connectToSortable', $(document).find('.keditor-container-content'));
            snippetsList.find('.keditor-snippet[data-type=container]').draggable('option', 'connectToSortable', $(document).find('.keditor-content-area'));
        }
    }
});

Hope it helps.

**Comment by ducdhm** [comment]
@Padawan2200 I added method for setContent dynamically. You can check at https://github.com/Kademi/keditor#how-to-set-content-of-keditor
