### ISSUE TITLE
Improve examples of keditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/keditor#98]
* Add basic example for enabling settings for container
 * Enable user to view source in example

Related to https://github.com/Kademi/keditor/issues/97, https://github.com/Kademi/keditor/issues/85

**Comment by ducdhm** [comment]
New button in example for viewing source:
![newui](https://user-images.githubusercontent.com/1289631/38912253-7a19c4ea-42fe-11e8-8f7f-ceb83f690cc2.png)

HTML tab in Source modal:
![newui2](https://user-images.githubusercontent.com/1289631/38912263-847ca218-42fe-11e8-8eb9-b510b4303adc.png)

JS tab in Source modal:
![newui3](https://user-images.githubusercontent.com/1289631/38912270-8929a702-42fe-11e8-9fc8-f3ee59a4ba95.png)

**Comment by lstandish** [comment]
At some point the "View source" button in the examples has been broken.  It shows only the original editor content loaded from the html file.  It does not reflect the content of the editor after changes/additions have been made.  This is true for the head of both the master branch and the gen-2 branch.

**Comment by bradmac** [comment]
Thanks for the heads up, will take a look over the next couple of weeks.

**Comment by lstandish** [comment]
Hi Brad, I fixed the problem and made a pull request.  I think my fix is complete and clean and can be committed. 

In sum, the code that grabbed the content area was in the wrong place.  It was in the modal setup code which is only executed once, on page load.  Therefore it loaded only the html on the page, not the editor content.  To fix this I moved the code to the click function.

I also had to change the function call to grab the editor content, from 
`htmlCode = $('[data-keditor="html"]').html();` to 
`htmlCode = $('#content-area').keditor('getContent');`

**Comment by bradmac** [comment]
@ducdhm could you take a look?

**Comment by ducdhm** [comment]
> At some point the "View source" button in the examples has been broken. It shows only the original editor content loaded from the html file. It does not reflect the content of the editor after changes/additions have been made. This is true for the head of both the master branch and the gen-2 branch.

I have checked and seem like it doesn't look like `View source` feature. The main functionality of this button is view original source code of current example. For getting current content, I can add other button for it. So I'll revert the pull request

**Comment by ducdhm** [comment]
Done!

**Comment by lstandish** [comment]
Hi ducdhm, I'm glad to see you're back to work on this project!

I don't understand. From ducdhm's comment, it appears that my pull request was reverted. (That means applied and then undone, right?) However, when I compare my forked gen-2 branch with the current Kademi gen-2 branch, I see no differences. Did you change your mind about reverting the pull request? Or have you just not done the revert yet?

I want to point out that before my changes to the "View Source" button code, it only showed the original html of the textarea on the page at the time it is first loaded, not any html added or changed via the editor. In other words, it had nothing to do with the editor.  On the other hand, my changes allow the button to show both the original textarea html as well as any subsequent changes to the html done through the editor.  In other words, the current html of the page.

**Comment by lstandish** [comment]
Sorry, I was away on a road trip for 2 weeks.

The "view source" button as I modified it **does** show the content of the html textarea when the page is first loaded.  And then, as content is edited, it shows the current edited content.  I don't think an additional button to show the original html content before any edits is useful to a developer.

Anyway, the decision on what to keep and what to add is of course yours.  Thanks for making this project open source.

**Comment by lstandish** [comment]
@ducdhm, I finally got a chance to look at your commit #98, in which you added a "Get content" button, based on my modifications to "fix" your previous "View source" button to show the current editor source code.

I now think that, since English is not your first language,  you don't have a clear understanding of what users normally expect when they see a "View source" button in an html editor.  In an editor context, "View source" is expected to show the **current editor source code,** not the "original" content before editing takes place.  I think you are understanding the word "source" to mean "original," and in this context, I do not believe that is the case. It is instead a reference to "source code."  If you don't believe me, ask any other native English-speaking developer for his or her opinion.

Furthermore, as I pointed out, no developer or end user needs or wants a button to display the contentarea field before editing takes place. However, if you insist on having it, I think you should rename the "View source" button to "View original" or similar.  Having both "View source" and "Get content" buttons is confusing, since to English-speaking users, these two actions are the same.

Finally, I think my contribution of code to provide a working "Get content" or "Show source" button (whatever you prefer to call it), plus also fixing prettyPrint, was important.  However, the way you handled my pull request was simply to revert (discard) it and use my ideas in a new commit of your own, rather than pull my commit and then modify it, as I think you should have done.  As a result I am not credited in the git history with contributing a **single line of code** to your project. Did you even realize that?

If you think my disappointment is unwarranted, just ask any other open source code contributor.  What's worse, this was my **first** commit.  After this treatment, it is hard to feel motivated to make further commits.

**Comment by ducdhm** [comment]
Hi @lstandish, 

1. I got your point now. Maybe "View source" should be changed to "View config".
2. I dont reverted your pull request. You can check it at [here](https://github.com/Kademi/keditor/pull/129)
3. Your pull request is in `gen-2` branch not `master`

If you're disappointed on me, I'm really sorry. I hope you will contribute for this project in future.

/Duc
